version: '3.8'

services:

  nginx:
    container_name: excel__nginx
    build: ./docker/nginx
    volumes:
      - .:/app:delegated
    ports:
      - 8889:80

  php-fpm:
    container_name: excel__php-fpm
    build: ./docker/php-fpm
    volumes:
      - .:/app:delegated
    ports:
      - 9002:9000

  php-cli:
    container_name: excel__php-cli
    build: ./docker/php-cli
    volumes:
      - .:/app:delegated
      - composer_cache:/home/appuser/.composer/cache:delegated

  mysql:
    container_name: excel__mysql
    build: ./docker/mysql
    volumes:
      - mysql_data:/var/lib/mysql:delegated
    command: --sql_mode=""
    environment:
      MYSQL_USER: excel
      MYSQL_ROOT_PASSWORD: root
      MYSQL_PASSWORD: excel
      MYSQL_DATABASE: laravel_import_export
      SERVICE_NAME: mysql
      TZ: Europe/Moscow
    restart: unless-stopped
    tty: true
    ports:
      - 3309:3306

  phpmyadmin:
    container_name: excel__phpmyadmin
    image: phpmyadmin/phpmyadmin:latest
    ports:
      - 8021:80
    environment:
      - PMA_ARBITRARY=1
      - PMA_HOST=mysql
      - UPLOAD_LIMIT=300M
    depends_on:
      - mysql

volumes:
  mysql_data:
  composer_cache:
  redis_data:
